name: dailysync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_staggered_grid_view: ^0.7.0
  percent_indicator: ^4.2.5
  animated_text_kit: ^4.3.0
  fl_chart: ^1.1.0
  confetti: ^0.8.0
  cloud_firestore: ^6.0.3
  liquid_progress_indicator_v2: ^0.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
